package isolette.system_tests.rst

import org.sireum._

// do not edit, auto-generated by p.Creator

class Example_Regulate_Subsystem_Outputs_Container_DSC_Test_Harness
  extends Regulate_Subsystem_Outputs_Container_DSC_Test_Harness {

  override def next(): isolette.system_tests.rst.Regulate_Subsystem_Outputs_Container = {
    halt("FYTD")
  }

  override def test(o: isolette.system_tests.rst.Regulate_Subsystem_Outputs_Container): B = {
    halt("FYTD")
  }


  override def string: String = toString

  override def $clonable: Boolean = F

  override def $clonable_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $owned: Boolean = F

  override def $owned_=(b: Boolean): org.sireum.$internal.MutableMarker = this

  override def $clone: org.sireum.$internal.MutableMarker = this
}
